// Auto-generated from data/brokers.json. Do not edit by hand.
window.BROKERS = [
  {
    "id": "acxiom",
    "name": "Acxiom (LiveRamp)",
    "category": "data_broker",
    "privacy_email": "askprivacy@acxiom.com",
    "privacy_url": "https://isapps.acxiom.com/optout/optout.aspx",
    "method": "email",
    "risk_level": "critical",
    "notes": "Data aggregation platform (Omnicom subsidiary). Previous email consumeradvo@acxiom.com retired June 30, 2025. Use askprivacy@acxiom.com. Compiles consumer profiles from public and commercial sources.",
    "pack": "critical"
  },
  {
    "id": "oracle_datacloud",
    "name": "Oracle Data Cloud",
    "category": "data_broker",
    "privacy_email": "privacy_ww@oracle.com",
    "privacy_url": "https://www.oracle.com/legal/privacy/privacy-choices.html",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Oracle Advertising division (BlueKai, Datalogix, AddThis) shut down September 30, 2024. Registry no longer available. Marketing/sales database deletion requests still processed via email.",
    "pack": "critical"
  },
  {
    "id": "epsilon",
    "name": "Epsilon (Publicis)",
    "category": "data_broker",
    "privacy_email": "privacy@epsilon.com",
    "privacy_url": "https://legal.epsilon.com/dsr/",
    "method": "portal",
    "risk_level": "critical",
    "notes": "Marketing data giant. Profiles on 250M+ Americans. Email requests refused. Must use Consumer Privacy Portal or call 1-866-267-3861 (Mon-Fri 9AM-5PM ET).",
    "pack": "critical"
  },
  {
    "id": "experian_marketing",
    "name": "Experian Marketing Services",
    "category": "data_broker",
    "privacy_email": "privacy@experian.com",
    "privacy_url": "https://www.experian.com/privacy/opting_out",
    "method": "email",
    "risk_level": "critical",
    "notes": "Consumer data beyond credit reports -- marketing profiles.",
    "pack": "critical"
  },
  {
    "id": "lexisnexis",
    "name": "LexisNexis Risk Solutions",
    "category": "data_broker",
    "privacy_email": "privacy.information.mgr@lexisnexis.com",
    "privacy_url": "https://optout.lexisnexis.com/",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Public records aggregator providing identity verification, background screening, and risk assessment services. Maintains extensive consumer data profiles.",
    "pack": "critical"
  },
  {
    "id": "spokeo",
    "name": "Spokeo",
    "category": "data_broker",
    "privacy_email": "privacy@spokeo.com",
    "privacy_url": "https://www.spokeo.com/optout",
    "method": "portal",
    "risk_level": "elevated",
    "notes": "People search engine aggregating social media profiles and public records. Claims public data is exempt from state privacy laws. Must use self-service opt-out tool. Court expungement orders required for criminal/court records.",
    "pack": "data_broker"
  },
  {
    "id": "whitepages",
    "name": "Whitepages (Ekata)",
    "category": "data_broker",
    "privacy_email": "support@whitepages.com",
    "privacy_url": "https://www.whitepages.com/suppression_requests",
    "method": "portal",
    "risk_level": "high_priority",
    "notes": "People search service. Opt out using the suppression link. Requires confirming a code via an automated voice call to your phone. Also owns 411.com.",
    "pack": "critical"
  },
  {
    "id": "beenverified",
    "name": "BeenVerified",
    "category": "data_broker",
    "privacy_email": "privacy@beenverified.com",
    "privacy_url": "https://www.beenverified.com/app/optout/search",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "People search aggregator. Maintains publicly listed removal request process. Collects data from public records, social media, and commercial sources.",
    "pack": "data_broker"
  },
  {
    "id": "intelius",
    "name": "Intelius",
    "category": "data_broker",
    "privacy_email": "support@mailer.intelius.com",
    "privacy_url": "https://suppression.peopleconnect.us/login",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "People search database. Opt out by emailing support@mailer.intelius.com, calling 1-888-245-1655, or filling out the suppression form. Owns Addresses.com, Instant Checkmate, Truthfinder, US Search, and more.",
    "pack": "critical"
  },
  {
    "id": "radaris",
    "name": "Radaris",
    "category": "data_broker",
    "privacy_email": "customer-service@radaris.com",
    "privacy_url": "https://radaris.com/control/privacy",
    "method": "portal",
    "risk_level": "high_priority",
    "notes": "People search service. Copy your profile URL and complete the online forms. If it fails, email your profile details/screenshot directly to customer-service@radaris.com.",
    "pack": "critical"
  },
  {
    "id": "peopledatalabs",
    "name": "People Data Labs",
    "category": "data_broker",
    "privacy_email": "privacy@peopledatalabs.com",
    "privacy_url": "https://www.peopledatalabs.com/opt-out",
    "method": "email",
    "risk_level": "elevated",
    "notes": "B2B data enrichment provider maintaining approximately 1.5 billion person profiles compiled from public and commercial sources.",
    "pack": "data_broker"
  },
  {
    "id": "clearview",
    "name": "Clearview AI",
    "category": "data_broker",
    "privacy_email": "privacy@clearview.ai",
    "privacy_url": "https://clearview.ai/privacy/requests",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Facial recognition platform collecting biometric identifiers from publicly available online images. Subject to ACLU settlement (2022), UK ICO fine (2022), Australian OAIC finding (2021). Provides search services to law enforcement agencies.",
    "pack": "critical"
  },
  {
    "id": "google",
    "name": "Google",
    "category": "ad_network",
    "privacy_email": "support-en-consumer-data-request@google.com",
    "privacy_url": "https://myaccount.google.com/delete-services-or-account",
    "method": "web_form",
    "risk_level": "critical",
    "notes": "Search, ads, YouTube, Maps, Gmail data collection.",
    "pack": "critical"
  },
  {
    "id": "meta",
    "name": "Meta (Facebook/Instagram)",
    "category": "social_media",
    "privacy_email": "privacy@meta.com",
    "privacy_url": "https://www.facebook.com/help/contact/540977946302970",
    "method": "web_form",
    "risk_level": "high_priority",
    "notes": "Social media platform operating Facebook, Instagram, WhatsApp, Threads. CCPA requests via web form or mail: ATTN Privacy Operations, 1 Meta Way, Menlo Park CA 94025.",
    "pack": "social_media"
  },
  {
    "id": "amazon",
    "name": "Amazon",
    "category": "retail",
    "privacy_email": "ccpa-request@amazon.com",
    "privacy_url": "https://www.amazon.com/hz/privacy-central/data-requests",
    "method": "email",
    "risk_level": "critical",
    "notes": "Purchase history, Alexa recordings, browsing behavior.",
    "pack": "retail"
  },
  {
    "id": "twitter",
    "name": "X (Twitter)",
    "category": "social_media",
    "privacy_email": "privacy@x.com",
    "privacy_url": "https://help.twitter.com/en/forms/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Social media platform. Collects user interests, social connections, and location history data.",
    "pack": "social_media"
  },
  {
    "id": "tiktok",
    "name": "TikTok",
    "category": "social_media",
    "privacy_email": "privacy@tiktok.com",
    "privacy_url": "https://www.tiktok.com/legal/report/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Social media platform. Collects behavioral data, video viewing preferences, and device fingerprinting information.",
    "pack": "social_media"
  },
  {
    "id": "linkedin",
    "name": "LinkedIn (Microsoft)",
    "category": "social_media",
    "privacy_email": null,
    "privacy_url": "https://www.linkedin.com/mypreferences/d/categories/privacy",
    "method": "web_form",
    "risk_level": "elevated",
    "notes": "Microsoft subsidiary. Professional networking platform. CCPA requests via Settings > Data Privacy. Mail: 1000 W Maude Ave, Sunnyvale CA 94085.",
    "pack": "social_media"
  },
  {
    "id": "apple",
    "name": "Apple",
    "category": "search",
    "privacy_email": null,
    "privacy_url": "https://privacy.apple.com/",
    "method": "web_form",
    "risk_level": "standard",
    "notes": "Technology company. Generally privacy-forward practices. Data download available via privacy.apple.com.",
    "pack": "critical"
  },
  {
    "id": "samsung",
    "name": "Samsung",
    "category": "retail",
    "privacy_email": "privacy@samsung.com",
    "privacy_url": "https://www.samsung.com/us/account/privacy/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Consumer electronics. Smart TV viewing data, device telemetry, and app usage collected per privacy policy.",
    "pack": "retail"
  },
  {
    "id": "openai",
    "name": "OpenAI (ChatGPT)",
    "category": "ai_company",
    "privacy_email": "privacy@openai.com",
    "privacy_url": "https://privacy.openai.com/policies",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "AI model developer (ChatGPT, DALL-E, GPT-4). Collects conversation data. User inputs may be used for model training unless opted out via Settings. FTC investigation (2023) regarding data practices.",
    "pack": "ai_companies"
  },
  {
    "id": "anthropic",
    "name": "Anthropic (Claude)",
    "category": "ai_company",
    "privacy_email": "privacy@anthropic.com",
    "privacy_url": "https://www.anthropic.com/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "AI model developer (Claude). Retains conversation data. API inputs may be used for model improvement per terms of service.",
    "pack": "ai_companies"
  },
  {
    "id": "meta_ai",
    "name": "Meta AI (Llama)",
    "category": "ai_company",
    "privacy_email": "privacy@meta.com",
    "privacy_url": "https://www.facebook.com/help/contact/540977946302970",
    "method": "web_form",
    "risk_level": "high_priority",
    "notes": "AI model developer (Llama). Trains models on user-generated content from Meta platforms. CCPA requests via Privacy Center.",
    "pack": "ai_companies"
  },
  {
    "id": "midjourney",
    "name": "Midjourney",
    "category": "ai_company",
    "privacy_email": "privacy@midjourney.com",
    "privacy_url": "https://docs.midjourney.com/docs/data-deletion-request-form-and-faq",
    "method": "portal",
    "risk_level": "elevated",
    "notes": "AI image generation platform. Stores all prompts and generated images. Privacy email inbox is unmonitored. Must use automated deletion form.",
    "pack": "ai_companies"
  },
  {
    "id": "stability",
    "name": "Stability AI",
    "category": "ai_company",
    "privacy_email": "privacy@stability.ai",
    "privacy_url": "https://stability.ai/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "AI image generation platform. Stable Diffusion trained on LAION-5B dataset, which researchers found contained personal photographs collected without individual consent.",
    "pack": "ai_companies"
  },
  {
    "id": "perplexity",
    "name": "Perplexity AI",
    "category": "ai_company",
    "privacy_email": "privacy@perplexity.ai",
    "privacy_url": "https://perplexity.typeform.com/datarequest",
    "method": "email",
    "risk_level": "standard",
    "notes": "AI search platform. Deletion requests via Typeform. privacy@perplexity.ai monitored (24h urgent, 5 business days standard). Processes search queries and conversations.",
    "pack": "ai_companies"
  },
  {
    "id": "microsoft_ai",
    "name": "Microsoft (Copilot/Bing)",
    "category": "ai_company",
    "privacy_email": null,
    "privacy_url": "https://account.microsoft.com/privacy",
    "method": "web_form",
    "risk_level": "high_priority",
    "notes": "Technology company operating Bing, Copilot, Outlook, Xbox, LinkedIn. CCPA requests via Privacy Dashboard. Mail: ATTN CELA Privacy, One Microsoft Way, Redmond WA 98052.",
    "pack": "ai_companies"
  },
  {
    "id": "google_ai",
    "name": "Google (Gemini/Bard)",
    "category": "ai_company",
    "privacy_email": null,
    "privacy_url": "https://myaccount.google.com/data-and-privacy",
    "method": "web_form",
    "risk_level": "critical",
    "notes": "Gemini conversations stored. Combined with search, Maps, Gmail, YouTube profiles.",
    "pack": "ai_companies"
  },
  {
    "id": "adobe_ai",
    "name": "Adobe (Firefly)",
    "category": "ai_company",
    "privacy_email": "privacy@adobe.com",
    "privacy_url": "https://www.adobe.com/privacy/California-CCPA.html",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Creative software platform. Firefly AI trained on licensed and user-contributed content. Collects document metadata and usage analytics.",
    "pack": "ai_companies"
  },
  {
    "id": "runway_ai",
    "name": "Runway ML",
    "category": "ai_company",
    "privacy_email": "privacy@runwayml.com",
    "privacy_url": "https://runwayml.com/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "AI video generation platform. Stores uploaded media and generated content.",
    "pack": "ai_companies"
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "category": "ai_company",
    "privacy_email": "privacy@elevenlabs.io",
    "privacy_url": "https://elevenlabs.io/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "AI voice synthesis platform. Stores uploaded voice samples. Technology enables generation of synthetic voice content.",
    "pack": "ai_companies"
  },
  {
    "id": "heygen_broker",
    "name": "HeyGen",
    "category": "ai_company",
    "privacy_email": "privacy@heygen.com",
    "privacy_url": "https://www.heygen.com/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "AI video/avatar platform. Collects facial data and voice recordings for avatar generation. Processes biometric identifiers.",
    "pack": "ai_companies"
  },
  {
    "id": "flock_safety",
    "name": "Flock Safety",
    "category": "surveillance",
    "privacy_email": "privacy@flocksafety.com",
    "privacy_url": "https://www.flocksafety.com/privacy-policy",
    "method": "email",
    "risk_level": "critical",
    "notes": "ALPR cameras tracking every car. Claims service-provider status to dodge CCPA. Must contact deploying agency directly.",
    "pack": "surveillance"
  },
  {
    "id": "palantir",
    "name": "Palantir Technologies",
    "category": "surveillance",
    "privacy_email": "privacy@palantir.com",
    "privacy_url": "https://www.palantir.com/privacy-and-security/",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Data analytics platform providing software to government agencies including defense and immigration enforcement. Integrates data from multiple public and private sources.",
    "pack": "surveillance"
  },
  {
    "id": "ring_amazon",
    "name": "Ring (Amazon)",
    "category": "surveillance",
    "privacy_email": "ccpa-request@amazon.com",
    "privacy_url": "https://www.amazon.com/hz/privacy-central/data-requests",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Amazon subsidiary. Smart doorbell/camera network. EFF reported data sharing agreements with over 2,000 law enforcement agencies. Ring changed policies in 2023 to require warrants.",
    "pack": "surveillance"
  },
  {
    "id": "fog_data",
    "name": "Fog Data Science",
    "category": "surveillance",
    "privacy_email": "info@fogdatascience.com",
    "privacy_url": "https://www.fogdatascience.com/contact",
    "method": "portal",
    "risk_level": "critical",
    "notes": "Sells location data to law enforcement without warrants. Does NOT collect PII (names, emails). Tracks Mobile Advertising IDs (MAIDs). Must submit your device MAID via opt-out form on website or reply to info@ with MAID.",
    "pack": "surveillance"
  },
  {
    "id": "babel_street",
    "name": "Babel Street",
    "category": "surveillance",
    "privacy_email": "privacy@babelstreet.com",
    "privacy_url": "https://www.babelstreet.com/privacy-policy",
    "method": "portal",
    "risk_level": "critical",
    "notes": "Location intelligence. Locate X product tracks phone locations. Sold to government agencies. Email requests redirected to Data Subject Access Rights Portal.",
    "pack": "surveillance"
  },
  {
    "id": "motorola_solutions",
    "name": "Motorola Solutions (Vigilant)",
    "category": "surveillance",
    "privacy_email": "privacy@motorolasolutions.com",
    "privacy_url": "https://www.motorolasolutions.com/about/privacy-policy.html",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Law enforcement technology. Operates Vigilant Solutions ALPR (Automatic License Plate Recognition) database used by police agencies.",
    "pack": "surveillance"
  },
  {
    "id": "axon",
    "name": "Axon (Taser/Evidence.com)",
    "category": "surveillance",
    "privacy_email": "privacy@axon.com",
    "privacy_url": "https://www.axon.com/legal/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Law enforcement technology company. Manufactures body cameras, conducted energy devices, and operates Evidence.com cloud storage platform for police agencies.",
    "pack": "surveillance"
  },
  {
    "id": "shotspotter",
    "name": "SoundThinking (ShotSpotter)",
    "category": "surveillance",
    "privacy_email": "privacy@soundthinking.com",
    "privacy_url": "https://www.soundthinking.com/privacy-policy/",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Acoustic detection platform (formerly ShotSpotter). Deploys audio sensors in neighborhoods for gunshot detection. Accuracy and civil liberties concerns raised by ACLU and others.",
    "pack": "surveillance"
  },
  {
    "id": "nextdoor",
    "name": "Nextdoor",
    "category": "surveillance",
    "privacy_email": "privacy@nextdoor.com",
    "privacy_url": "https://help.nextdoor.com/s/article/CCPA",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Neighborhood social network. Collects home addresses and location data. Has established data-sharing programs with local law enforcement agencies.",
    "pack": "surveillance"
  },
  {
    "id": "cellebrite",
    "name": "Cellebrite",
    "category": "surveillance",
    "privacy_email": "privacy@cellebrite.com",
    "privacy_url": "https://cellebrite.com/en/privacy-policy/",
    "method": "email",
    "risk_level": "critical",
    "notes": "Phone forensics tools. Extracts all data from mobile devices. Used by law enforcement worldwide.",
    "pack": "surveillance"
  },
  {
    "id": "gravy_analytics",
    "name": "Gravy Analytics",
    "category": "location_broker",
    "privacy_email": "privacy@gravyanalytics.com",
    "privacy_url": null,
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Location data aggregator. Subject to FTC enforcement action (2024) regarding collection and sale of geolocation data associated with sensitive locations including healthcare facilities.",
    "pack": "location_brokers"
  },
  {
    "id": "xmode_outlogic",
    "name": "X-Mode Social (Outlogic)",
    "category": "location_broker",
    "privacy_email": "privacy@outlogic.io",
    "privacy_url": "https://outlogic.io/privacy-policy",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Location data company (rebranded as Outlogic). Vice News (2020) reported data from apps including Muslim prayer apps was provided to defense contractors. Company subsequently rebranded.",
    "pack": "location_brokers"
  },
  {
    "id": "safegraph",
    "name": "SafeGraph",
    "category": "location_broker",
    "privacy_email": "privacy@safegraph.com",
    "privacy_url": "https://www.safegraph.com/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Location data aggregator. Compiled geolocation data from mobile apps. ProPublica and other outlets reported data included visits to sensitive locations.",
    "pack": "location_brokers"
  },
  {
    "id": "placer_ai",
    "name": "Placer.ai",
    "category": "location_broker",
    "privacy_email": "privacy@placer.ai",
    "privacy_url": "https://www.placer.ai/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Location analytics platform. Aggregates anonymized mobile device signals to measure foot traffic patterns at commercial locations.",
    "pack": "location_brokers"
  },
  {
    "id": "cuebiq",
    "name": "Cuebiq (Spectus)",
    "category": "location_broker",
    "privacy_email": "privacy@spectus.ai",
    "privacy_url": "https://spectus.ai/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Location intelligence platform (rebranded as Spectus). Aggregates mobile device movement patterns for analytics.",
    "pack": "location_brokers"
  },
  {
    "id": "near_intelligence",
    "name": "Near Intelligence",
    "category": "location_broker",
    "privacy_email": "privacy@near.com",
    "privacy_url": null,
    "method": "email",
    "risk_level": "elevated",
    "notes": "Location data company. Reported to have compiled data from approximately 1.6 billion devices. Filed for bankruptcy in 2023 following reporting on defense sector data sales.",
    "pack": "location_brokers"
  },
  {
    "id": "mobilewalla",
    "name": "Mobilewalla",
    "category": "location_broker",
    "privacy_email": "privacy@mobilewalla.com",
    "privacy_url": "https://www.mobilewalla.com/privacy-policy",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Mobile device data aggregator. Reported by WSJ (2020) and The Intercept to have provided geolocation data analytics of protest attendees and public gatherings.",
    "pack": "location_brokers"
  },
  {
    "id": "flo_health",
    "name": "Flo Health (Period Tracker)",
    "category": "health_data",
    "privacy_email": "privacy@flo.health",
    "privacy_url": "https://flo.health/privacy-policy",
    "method": "email",
    "risk_level": "critical",
    "notes": "Period tracking app. FTC settlement for sharing health data with Facebook and Google despite promises.",
    "pack": "health_data"
  },
  {
    "id": "grindr",
    "name": "Grindr",
    "category": "health_data",
    "privacy_email": "privacy@grindr.com",
    "privacy_url": "https://www.grindr.com/privacy-policy",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Social/dating application. Norwegian DPA fined €6.5M (2021) for sharing user health status and precise geolocation data with third-party advertising partners.",
    "pack": "health_data"
  },
  {
    "id": "goodrx",
    "name": "GoodRx",
    "category": "health_data",
    "privacy_email": "privacy@goodrx.com",
    "privacy_url": "https://www.goodrx.com/privacy-policy",
    "method": "email",
    "risk_level": "critical",
    "notes": "FTC .5M fine for sharing prescription data with Meta and Google for ad targeting.",
    "pack": "health_data"
  },
  {
    "id": "betterhelp",
    "name": "BetterHelp",
    "category": "health_data",
    "privacy_email": "privacy@betterhelp.com",
    "privacy_url": "https://www.betterhelp.com/privacy-policy/",
    "method": "email",
    "risk_level": "critical",
    "notes": "FTC .8M fine for sharing therapy intake data with Facebook, Snapchat, Criteo for ads.",
    "pack": "health_data"
  },
  {
    "id": "cerebral",
    "name": "Cerebral",
    "category": "health_data",
    "privacy_email": "privacy@cerebral.com",
    "privacy_url": "https://cerebral.com/privacy",
    "method": "email",
    "risk_level": "critical",
    "notes": "Mental health startup. Shared 3.1M patients data with ad platforms via tracking pixels.",
    "pack": "health_data"
  },
  {
    "id": "noom",
    "name": "Noom",
    "category": "health_data",
    "privacy_email": "privacy@noom.com",
    "privacy_url": "https://www.noom.com/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Health and weight management app. Collects dietary, exercise, and psychological assessment data. Privacy policy permits sharing aggregated data with advertising partners.",
    "pack": "health_data"
  },
  {
    "id": "myfitnesspal",
    "name": "MyFitnessPal (Under Armour)",
    "category": "health_data",
    "privacy_email": "privacy@myfitnesspal.com",
    "privacy_url": "https://www.myfitnesspal.com/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Fitness and nutrition tracking app (Under Armour). 2018 data breach affected approximately 150 million user accounts.",
    "pack": "health_data"
  },
  {
    "id": "23andme",
    "name": "23andMe",
    "category": "health_data",
    "privacy_email": "privacy@23andme.com",
    "privacy_url": "https://www.23andme.com/legal/privacy/",
    "method": "email",
    "risk_level": "critical",
    "notes": "Genetic data. Near-bankruptcy raised fears about data sale. 6.9M users genetic data breached 2023.",
    "pack": "health_data"
  },
  {
    "id": "character_ai",
    "name": "Character.AI",
    "category": "ai_company",
    "privacy_email": "privacy@character.ai",
    "privacy_url": "https://character.ai/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Conversational AI platform. Stores all user interactions and character conversations. Significant usage among minors per NYT reporting (2023).",
    "pack": "ai_companies"
  },
  {
    "id": "inflection_pi",
    "name": "Inflection AI (Pi)",
    "category": "ai_company",
    "privacy_email": "privacy@inflection.ai",
    "privacy_url": "https://inflection.ai/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Conversational AI assistant. Retains conversation history. May use interaction data for model improvement.",
    "pack": "ai_companies"
  },
  {
    "id": "xai_grok",
    "name": "xAI (Grok)",
    "category": "ai_company",
    "privacy_email": "privacy@x.ai",
    "privacy_url": "https://x.ai/legal/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "AI company (xAI). Grok model trained using data from X (Twitter) platform. Cross-references social media activity.",
    "pack": "ai_companies"
  },
  {
    "id": "cohere",
    "name": "Cohere",
    "category": "ai_company",
    "privacy_email": "privacy@cohere.com",
    "privacy_url": "https://cohere.com/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Enterprise AI platform. API inputs may be retained for model improvement unless customer opts out per enterprise agreement.",
    "pack": "ai_companies"
  },
  {
    "id": "jasper_ai",
    "name": "Jasper AI",
    "category": "ai_company",
    "privacy_email": "privacy@jasper.ai",
    "privacy_url": "https://www.jasper.ai/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "AI writing assistant. Stores user prompts and generated content for service improvement.",
    "pack": "ai_companies"
  },
  {
    "id": "samsung_ai",
    "name": "Samsung (Bixby/Galaxy AI)",
    "category": "ai_company",
    "privacy_email": "privacy@samsung.com",
    "privacy_url": "https://account.samsung.com/membership/terms/privacypolicy",
    "method": "web_form",
    "risk_level": "elevated",
    "notes": "Consumer electronics. Galaxy AI features transmit voice data and device content to Samsung servers for processing. Collects device telemetry.",
    "pack": "ai_companies"
  },
  {
    "id": "apple_ai",
    "name": "Apple (Siri/Apple Intelligence)",
    "category": "ai_company",
    "privacy_email": "privacy@apple.com",
    "privacy_url": "https://privacy.apple.com/",
    "method": "web_form",
    "risk_level": "standard",
    "notes": "On-device AI processing (Apple Intelligence). Siri voice transcripts may be retained. CCPA requests via privacy.apple.com.",
    "pack": "ai_companies"
  },
  {
    "id": "amazon_alexa",
    "name": "Amazon (Alexa)",
    "category": "ai_company",
    "privacy_email": "privacy@amazon.com",
    "privacy_url": "https://www.amazon.com/gp/help/customer/display.html?nodeId=GX7NJR4FB4FXRK98",
    "method": "web_form",
    "risk_level": "elevated",
    "notes": "Amazon subsidiary. Voice assistant storing voice recordings and interaction history. Integrates with Ring home security ecosystem.",
    "pack": "ai_companies"
  },
  {
    "id": "snapchat",
    "name": "Snapchat",
    "category": "social_media",
    "privacy_email": "privacy@snap.com",
    "privacy_url": "https://accounts.snapchat.com/accounts/downloadmydata",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Social media platform. Snap Map feature shares user location. Camera features process facial geometry. Retains message metadata.",
    "pack": "social_media"
  },
  {
    "id": "discord",
    "name": "Discord",
    "category": "social_media",
    "privacy_email": "privacy@discord.com",
    "privacy_url": "https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360000029731",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Communication platform. Retains all message content and voice channel metadata indefinitely per terms of service.",
    "pack": "social_media"
  },
  {
    "id": "reddit",
    "name": "Reddit",
    "category": "social_media",
    "privacy_email": "reddit-privacy@reddit.com",
    "privacy_url": "https://www.reddit.com/settings/data-request",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Social platform. Entered content licensing agreements with AI companies including Google and OpenAI for training data access.",
    "pack": "social_media"
  },
  {
    "id": "pinterest",
    "name": "Pinterest",
    "category": "social_media",
    "privacy_email": "privacy@pinterest.com",
    "privacy_url": "https://help.pinterest.com/en/article/submit-a-privacy-request",
    "method": "email",
    "risk_level": "standard",
    "notes": "Visual discovery platform. Collects interest and browsing data. Pinterest Tag tracks user activity across partner websites.",
    "pack": "social_media"
  },
  {
    "id": "twitch",
    "name": "Twitch (Amazon)",
    "category": "social_media",
    "privacy_email": "privacy@twitch.tv",
    "privacy_url": "https://www.twitch.tv/p/en/legal/privacy-choices/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Live streaming platform (Amazon subsidiary). Collects chat logs, viewing habits, and purchase data. Integrated with Amazon user profile.",
    "pack": "social_media"
  },
  {
    "id": "telegram",
    "name": "Telegram",
    "category": "social_media",
    "privacy_email": "privacy@telegram.org",
    "privacy_url": "https://telegram.org/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Messaging platform. Cloud-based chats stored on servers. End-to-end encryption available only in Secret Chat mode.",
    "pack": "social_media"
  },
  {
    "id": "wyze",
    "name": "Wyze",
    "category": "surveillance",
    "privacy_email": "privacy@wyze.com",
    "privacy_url": "https://wyze.com/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Smart home camera company. 2024 security incident resulted in approximately 13,000 users briefly seeing other users camera feeds (Wyze disclosure, Feb 2024).",
    "pack": "surveillance"
  },
  {
    "id": "arlo",
    "name": "Arlo",
    "category": "surveillance",
    "privacy_email": "privacy@arlo.com",
    "privacy_url": "https://www.arlo.com/en-us/about/privacy-policy/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Cloud-connected home security cameras. Video stored on Arlo servers. Offers optional facial recognition features.",
    "pack": "surveillance"
  },
  {
    "id": "clearview_alt",
    "name": "PimEyes",
    "category": "surveillance",
    "privacy_email": "privacy@pimeyes.com",
    "privacy_url": "https://pimeyes.com/en/removal",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Facial recognition search engine allowing reverse image searches of human faces across publicly available internet images. Banned in several EU jurisdictions.",
    "pack": "surveillance"
  },
  {
    "id": "verkada",
    "name": "Verkada",
    "category": "surveillance",
    "privacy_email": "privacy@verkada.com",
    "privacy_url": "https://www.verkada.com/privacy/",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Enterprise security camera platform with AI analytics. 2021 security breach exposed feeds from approximately 150,000 cameras at various facilities (Bloomberg, March 2021).",
    "pack": "surveillance"
  },
  {
    "id": "peloton",
    "name": "Peloton",
    "category": "health_data",
    "privacy_email": "privacy@onepeloton.com",
    "privacy_url": "https://www.onepeloton.com/privacy-policy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Connected fitness platform. Collects workout data, heart rate, and location. Privacy policy permits sharing aggregated data.",
    "pack": "health_data"
  },
  {
    "id": "oura",
    "name": "Oura Ring",
    "category": "health_data",
    "privacy_email": "privacy@ouraring.com",
    "privacy_url": "https://ouraring.com/privacy-policy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Wearable health device. Collects sleep, HRV, temperature, SpO2, and activity data. Syncs biometric data to cloud servers.",
    "pack": "health_data"
  },
  {
    "id": "whoop",
    "name": "WHOOP",
    "category": "health_data",
    "privacy_email": "privacy@whoop.com",
    "privacy_url": "https://www.whoop.com/privacy/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Wearable health device. Continuous biometric monitoring including strain, recovery, and sleep metrics. All data stored in cloud.",
    "pack": "health_data"
  },
  {
    "id": "strava",
    "name": "Strava",
    "category": "health_data",
    "privacy_email": "privacy@strava.com",
    "privacy_url": "https://www.strava.com/legal/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Fitness tracking platform. GPS route and location data. 2018: Strava Global Heatmap inadvertently revealed activity at sensitive government facilities.",
    "pack": "health_data"
  },
  {
    "id": "calm",
    "name": "Calm",
    "category": "health_data",
    "privacy_email": "privacy@calm.com",
    "privacy_url": "https://www.calm.com/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Mental wellness application. Collects meditation activity, mood tracking inputs, and sleep data.",
    "pack": "health_data"
  },
  {
    "id": "headspace",
    "name": "Headspace",
    "category": "health_data",
    "privacy_email": "privacy@headspace.com",
    "privacy_url": "https://www.headspace.com/privacy-policy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Mental health and meditation application. Collects session data, mood logs, and usage patterns.",
    "pack": "health_data"
  },
  {
    "id": "doordash",
    "name": "DoorDash",
    "category": "retail",
    "privacy_email": "privacy@doordash.com",
    "privacy_url": "https://help.doordash.com/consumers/s/privacy-and-security",
    "method": "email",
    "risk_level": "standard",
    "notes": "Food delivery platform. Collects location, order history, and dietary preference data. Privacy policy permits sharing with restaurant partners and advertisers.",
    "pack": "retail"
  },
  {
    "id": "uber",
    "name": "Uber",
    "category": "retail",
    "privacy_email": "privacy@uber.com",
    "privacy_url": "https://privacy.uber.com/privacy/california",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Ride-sharing platform. Collects continuous GPS location during trips. Maintains trip history and payment data.",
    "pack": "retail"
  },
  {
    "id": "venmo",
    "name": "Venmo (PayPal)",
    "category": "finance",
    "privacy_email": "privacy@paypal.com",
    "privacy_url": "https://www.paypal.com/us/webapps/mpp/ua/privacy-full",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Payment platform (PayPal subsidiary). Transaction activity is set to public visibility by default. Maintains social graph of payment relationships.",
    "pack": "retail"
  },
  {
    "id": "cashapp",
    "name": "Cash App (Block)",
    "category": "finance",
    "privacy_email": "privacy@squareup.com",
    "privacy_url": "https://cash.app/legal/us/en/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Mobile payment platform (Block, Inc.). Processes financial transactions and identity verification data.",
    "pack": "retail"
  },
  {
    "id": "equifax",
    "name": "Equifax",
    "category": "data_broker",
    "privacy_email": "privacy@equifax.com",
    "privacy_url": "https://www.equifax.com/personal/opt-out-of-prescreen-offers/",
    "method": "email",
    "risk_level": "critical",
    "notes": "Credit bureau. 2017 breach exposed 147 million people. Also operates data analytics and marketing services beyond credit reporting.",
    "pack": "critical"
  },
  {
    "id": "transunion",
    "name": "TransUnion",
    "category": "data_broker",
    "privacy_email": "privacy@transunion.com",
    "privacy_url": "https://www.transunion.com/consumer-privacy",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Credit bureau and data analytics company. Operates TLO and Signal divisions for marketing and identity verification data.",
    "pack": "data_broker"
  },
  {
    "id": "corelogic",
    "name": "CoreLogic",
    "category": "data_broker",
    "privacy_email": "privacy@corelogic.com",
    "privacy_url": "https://www.corelogic.com/about-us/privacy-statement/",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Property and real estate data aggregator. Maintains detailed profiles on property ownership, mortgage history, and home values for 99% of US properties.",
    "pack": "data_broker"
  },
  {
    "id": "truthfinder",
    "name": "TruthFinder",
    "category": "data_broker",
    "privacy_email": "privacy@truthfinder.com",
    "privacy_url": "https://www.truthfinder.com/opt-out/",
    "method": "email",
    "risk_level": "elevated",
    "notes": "People search engine. Aggregates criminal records, social media, contact info, and public records into searchable profiles.",
    "pack": "data_broker"
  },
  {
    "id": "peoplefinders",
    "name": "PeopleFinders",
    "category": "data_broker",
    "privacy_email": "privacy@peoplefinders.com",
    "privacy_url": "https://www.peoplefinders.com/opt-out",
    "method": "email",
    "risk_level": "elevated",
    "notes": "People search site. Compiles public records, addresses, phone numbers, and associates into searchable profiles.",
    "pack": "data_broker"
  },
  {
    "id": "ussearch",
    "name": "US Search",
    "category": "data_broker",
    "privacy_email": "privacy@ussearch.com",
    "privacy_url": "https://www.ussearch.com/opt-out/submit/",
    "method": "email",
    "risk_level": "standard",
    "notes": "People search service. Aggregates public records into background reports. Part of the PeopleFinders network.",
    "pack": "data_broker"
  },
  {
    "id": "mylife",
    "name": "MyLife",
    "category": "data_broker",
    "privacy_email": "privacy@mylife.com",
    "privacy_url": "https://www.mylife.com/privacyrequest",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "People search site with 'reputation scores.' Opt out via their online request page, or email privacy@mylife.com with your profile link. Phone removal available at (888) 704-1900.",
    "pack": "critical"
  },
  {
    "id": "zillow",
    "name": "Zillow",
    "category": "data_broker",
    "privacy_email": "privacy@zillow.com",
    "privacy_url": "https://www.zillow.com/z/corp/privacy/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Real estate platform. Collects home search history, financial pre-qualification data, and browsing behavior across Zillow, Trulia, and StreetEasy.",
    "pack": "retail"
  },
  {
    "id": "instacart",
    "name": "Instacart",
    "category": "retail",
    "privacy_email": "privacy@instacart.com",
    "privacy_url": "https://www.instacart.com/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Grocery delivery platform. Collects purchase history, dietary patterns, and delivery addresses. Shares data with retail partners.",
    "pack": "retail"
  },
  {
    "id": "lyft",
    "name": "Lyft",
    "category": "retail",
    "privacy_email": "privacy@lyft.com",
    "privacy_url": "https://www.lyft.com/privacy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Ride-sharing platform. Collects GPS location, trip history, and payment data. Maintains contact graphs from phone permissions.",
    "pack": "retail"
  },
  {
    "id": "walmart",
    "name": "Walmart",
    "category": "retail",
    "privacy_email": "privacy@walmart.com",
    "privacy_url": "https://corporate.walmart.com/privacy-security/california-privacy-rights",
    "method": "email",
    "risk_level": "standard",
    "notes": "Retail giant. Collects in-store and online purchase history, Walmart+ membership data, and pharmacy records.",
    "pack": "retail"
  },
  {
    "id": "target",
    "name": "Target",
    "category": "retail",
    "privacy_email": "privacy@target.com",
    "privacy_url": "https://www.target.com/c/california-privacy-rights/-/N-55pes",
    "method": "email",
    "risk_level": "standard",
    "notes": "Retail chain. Collects purchase history and browsing data. Known for predictive analytics on customer behavior patterns.",
    "pack": "retail"
  },
  {
    "id": "spotify",
    "name": "Spotify",
    "category": "social_media",
    "privacy_email": "privacy@spotify.com",
    "privacy_url": "https://www.spotify.com/us/privacy",
    "method": "email",
    "risk_level": "standard",
    "notes": "Music streaming platform. Collects listening history, mood inference data, and location. Shares data with advertisers on free tier.",
    "pack": "social_media"
  },
  {
    "id": "paypal",
    "name": "PayPal",
    "category": "finance",
    "privacy_email": "privacy@paypal.com",
    "privacy_url": "https://www.paypal.com/us/webapps/mpp/ua/privacy-full",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Payment platform. Processes financial transactions, maintains purchase history, and operates Honey browser extension for shopping behavior tracking.",
    "pack": "retail"
  },
  {
    "id": "robinhood",
    "name": "Robinhood",
    "category": "finance",
    "privacy_email": "privacy@robinhood.com",
    "privacy_url": "https://robinhood.com/us/en/about/legal/",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Investment platform. Collects financial data, trading behavior, and identity verification documents including SSN.",
    "pack": "retail"
  },
  {
    "id": "ancestry",
    "name": "Ancestry",
    "category": "health_data",
    "privacy_email": "privacy@ancestry.com",
    "privacy_url": "https://www.ancestry.com/cs/legal/privacystatement",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Genealogy and DNA testing. Stores genetic data and family tree information. Owns AncestryDNA database of millions of DNA samples.",
    "pack": "health_data"
  },
  {
    "id": "fitbit",
    "name": "Fitbit (Google)",
    "category": "health_data",
    "privacy_email": "privacy@fitbit.com",
    "privacy_url": "https://www.fitbit.com/legal/privacy-policy",
    "method": "email",
    "risk_level": "elevated",
    "notes": "Wearable fitness tracker (Google subsidiary). Biometric data including heart rate, sleep, SpO2, and GPS routes. Data now integrated into Google account.",
    "pack": "health_data"
  },
  {
    "id": "garmin",
    "name": "Garmin",
    "category": "health_data",
    "privacy_email": "privacy@garmin.com",
    "privacy_url": "https://www.garmin.com/en-US/privacy/connect/policy/",
    "method": "email",
    "risk_level": "standard",
    "notes": "Wearable and GPS device maker. Garmin Connect stores fitness, health, and location data. 2020 ransomware attack disrupted services.",
    "pack": "health_data"
  },
  {
    "id": "life360",
    "name": "Life360",
    "category": "location_broker",
    "privacy_email": "privacy@life360.com",
    "privacy_url": "https://www.life360.com/privacy_policy/",
    "method": "email",
    "risk_level": "high_priority",
    "notes": "Family location sharing app. The Markup (2021) reported sale of precise location data to brokers including X-Mode and SafeGraph. Tracks continuous GPS.",
    "pack": "location_brokers"
  },

  {"id": "chase", "name": "Chase (JPMorgan)", "category": "finance", "privacy_email": "privacy.officer@jpmchase.com", "privacy_url": "https://www.chase.com/digital/resources/privacy-security/privacy/ca-consumer-privacy-act", "method": "portal", "risk_level": "high_priority", "notes": "Largest US bank. Collects transaction data, spending habits, location from app usage, and shares with marketing partners.", "pack": "finance"},
  {"id": "wells_fargo", "name": "Wells Fargo", "category": "finance", "privacy_email": "privacy@wellsfargo.com", "privacy_url": "https://www.wellsfargo.com/privacy-security/privacy/california-consumer-privacy-act/", "method": "email", "risk_level": "high_priority", "notes": "Major US bank collecting financial behavior, location, device data. History of unauthorized account creation scandal.", "pack": "finance"},
  {"id": "bank_of_america", "name": "Bank of America", "category": "finance", "privacy_email": "california.privacy@bankofamerica.com", "privacy_url": "https://www.bankofamerica.com/security-center/ccpa-disclosure/", "method": "email", "risk_level": "high_priority", "notes": "Major US bank. Collects and shares financial data, browsing activity, and inferred demographics.", "pack": "finance"},
  {"id": "capital_one", "name": "Capital One", "category": "finance", "privacy_email": "privacy@capitalone.com", "privacy_url": "https://www.capitalone.com/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Major credit card issuer and bank. Collects spending patterns, location, device fingerprints.", "pack": "finance"},
  {"id": "amex", "name": "American Express", "category": "finance", "privacy_email": "privacy@aexp.com", "privacy_url": "https://www.americanexpress.com/us/company/privacy-center/", "method": "email", "risk_level": "high_priority", "notes": "Credit card company. Sells anonymized transaction data to merchants and advertisers via Amex Offers.", "pack": "finance"},
  {"id": "discover", "name": "Discover Financial", "category": "finance", "privacy_email": "privacy@discover.com", "privacy_url": "https://www.discover.com/privacy-statement/ccpa-notice/", "method": "email", "risk_level": "moderate", "notes": "Credit card and banking company. Collects transaction data, credit behavior, and device information.", "pack": "finance"},
  {"id": "sofi", "name": "SoFi", "category": "finance", "privacy_email": "privacy@sofi.com", "privacy_url": "https://www.sofi.com/privacy/", "method": "email", "risk_level": "moderate", "notes": "Fintech platform offering loans, investing, and banking. Collects financial behavior and app usage data.", "pack": "finance"},
  {"id": "plaid", "name": "Plaid", "category": "finance", "privacy_email": "privacy@plaid.com", "privacy_url": "https://plaid.com/legal/#consumers", "method": "email", "risk_level": "critical", "notes": "Financial data aggregator used by thousands of apps. Accesses bank account data, transaction history. Settled $58M class action in 2022 over data collection practices.", "pack": "finance"},
  {"id": "mint_intuit", "name": "Intuit (Mint/Credit Karma)", "category": "finance", "privacy_email": "privacy@intuit.com", "privacy_url": "https://www.intuit.com/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Owns TurboTax, Credit Karma, Mint. Collects tax returns, credit scores, financial transactions, and spending patterns.", "pack": "finance"},
  {"id": "coinbase", "name": "Coinbase", "category": "finance", "privacy_email": "privacy@coinbase.com", "privacy_url": "https://www.coinbase.com/legal/privacy", "method": "email", "risk_level": "high_priority", "notes": "Largest US crypto exchange. Collects identity documents, transaction history, wallet addresses, and device data.", "pack": "finance"},
  {"id": "credit_karma", "name": "Credit Karma", "category": "finance", "privacy_email": "privacy@creditkarma.com", "privacy_url": "https://www.creditkarma.com/about/privacy", "method": "email", "risk_level": "high_priority", "notes": "Free credit monitoring service (Intuit). Revenue from targeted financial product recommendations based on your credit profile.", "pack": "finance"},

  {"id": "google_ads", "name": "Google Ads (Alphabet)", "category": "ad_network", "privacy_email": "privacy@google.com", "privacy_url": "https://adssettings.google.com/", "method": "email", "risk_level": "critical", "notes": "World's largest ad network. Tracks browsing across 2M+ websites via DoubleClick/Google Ad Manager. Builds detailed interest profiles.", "pack": "ad_networks"},
  {"id": "meta_ads", "name": "Meta Audience Network", "category": "ad_network", "privacy_email": "privacy@meta.com", "privacy_url": "https://www.facebook.com/privacy/policy/", "method": "email", "risk_level": "critical", "notes": "Facebook/Instagram ad platform. Tracks users across apps and websites via Meta Pixel. Builds shadow profiles of non-users.", "pack": "ad_networks"},
  {"id": "trade_desk", "name": "The Trade Desk", "category": "ad_network", "privacy_email": "privacy@thetradedesk.com", "privacy_url": "https://www.thetradedesk.com/us/privacy", "method": "email", "risk_level": "high_priority", "notes": "Demand-side platform for programmatic advertising. Processes billions of ad impressions daily. Unified ID 2.0 initiative tracks users across the open internet.", "pack": "ad_networks"},
  {"id": "applovin", "name": "AppLovin", "category": "ad_network", "privacy_email": "privacy@applovin.com", "privacy_url": "https://www.applovin.com/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Mobile ad network and app monetization platform. Collects device identifiers, app usage, location, and behavioral data across thousands of apps.", "pack": "ad_networks"},
  {"id": "unity_ads", "name": "Unity Ads (ironSource)", "category": "ad_network", "privacy_email": "privacy@unity3d.com", "privacy_url": "https://unity.com/legal/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "In-game advertising platform. Tracks player behavior, device data, and engagement patterns across mobile games.", "pack": "ad_networks"},
  {"id": "criteo", "name": "Criteo", "category": "ad_network", "privacy_email": "privacy@criteo.com", "privacy_url": "https://www.criteo.com/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Retargeting ad network. Tracks browsing across e-commerce sites to serve personalized ads. Maintains shopper interest graphs.", "pack": "ad_networks"},
  {"id": "taboola", "name": "Taboola", "category": "ad_network", "privacy_email": "privacy@taboola.com", "privacy_url": "https://www.taboola.com/privacy-policy", "method": "email", "risk_level": "moderate", "notes": "Content recommendation and native advertising platform. Embedded on major news sites. Tracks reading habits and click behavior.", "pack": "ad_networks"},
  {"id": "outbrain", "name": "Outbrain", "category": "ad_network", "privacy_email": "privacy@outbrain.com", "privacy_url": "https://www.outbrain.com/privacy/", "method": "email", "risk_level": "moderate", "notes": "Content discovery platform. Shows sponsored content on news sites. Builds interest profiles from reading behavior.", "pack": "ad_networks"},
  {"id": "liveramp", "name": "LiveRamp", "category": "ad_network", "privacy_email": "privacy@liveramp.com", "privacy_url": "https://liveramp.com/opt_out/", "method": "portal", "risk_level": "critical", "notes": "Identity resolution platform connecting offline and online data. Links your real identity to browsing behavior across devices. Used by most major advertisers.", "pack": "ad_networks"},
  {"id": "lotame", "name": "Lotame", "category": "ad_network", "privacy_email": "privacy@lotame.com", "privacy_url": "https://www.lotame.com/about-lotame/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Data management platform. Collects and segments audience data across web, mobile, and connected TV for ad targeting.", "pack": "ad_networks"},
  {"id": "adobe_ads", "name": "Adobe Advertising Cloud", "category": "ad_network", "privacy_email": "privacy@adobe.com", "privacy_url": "https://www.adobe.com/privacy/opt-out.html", "method": "email", "risk_level": "high_priority", "notes": "Adobe's advertising platform. Combines Creative Cloud user data with ad targeting across web and connected TV.", "pack": "ad_networks"},
  {"id": "amazon_ads", "name": "Amazon Advertising", "category": "ad_network", "privacy_email": "privacy@amazon.com", "privacy_url": "https://www.amazon.com/adprefs", "method": "email", "risk_level": "critical", "notes": "Third-largest digital ad platform globally. Uses purchase history, browsing, Alexa, and Ring data for ad targeting.", "pack": "ad_networks"},

  {"id": "bing", "name": "Microsoft Bing", "category": "search", "privacy_email": "msiprivacy@microsoft.com", "privacy_url": "https://account.microsoft.com/privacy", "method": "email", "risk_level": "high_priority", "notes": "Second-largest search engine. Collects search queries, browsing via Edge, location, and Cortana voice data.", "pack": "search"},
  {"id": "yahoo", "name": "Yahoo (Apollo)", "category": "search", "privacy_email": "datasafety@yahooinc.com", "privacy_url": "https://legal.yahoo.com/us/en/yahoo/privacy/dashboard/index.html", "method": "portal", "risk_level": "high_priority", "notes": "Search, email, news portal. Scans email content for ad targeting. Shares data with advertising partners.", "pack": "search"},
  {"id": "duckduckgo", "name": "DuckDuckGo", "category": "search", "privacy_email": "privacy@duckduckgo.com", "privacy_url": "https://duckduckgo.com/privacy", "method": "email", "risk_level": "low", "notes": "Privacy-focused search engine. Does not track users or build profiles. Included for completeness.", "pack": "search"},
  {"id": "brave_search", "name": "Brave Search", "category": "search", "privacy_email": "privacy@brave.com", "privacy_url": "https://brave.com/privacy/browser/", "method": "email", "risk_level": "low", "notes": "Privacy-focused search and browser. Minimal data collection. Included for completeness.", "pack": "search"},
  {"id": "yelp", "name": "Yelp", "category": "search", "privacy_email": "privacy@yelp.com", "privacy_url": "https://www.yelp.com/tos/privacy_policy", "method": "email", "risk_level": "moderate", "notes": "Local business search. Collects reviews, check-ins, search queries, and location data. Shares with advertising partners.", "pack": "search"},
  {"id": "startpage", "name": "Startpage", "category": "search", "privacy_email": "privacy@startpage.com", "privacy_url": "https://www.startpage.com/en/privacy-policy", "method": "email", "risk_level": "low", "notes": "Privacy search engine using Google results without tracking. Minimal data retention.", "pack": "search"},
  {"id": "ecosia", "name": "Ecosia", "category": "search", "privacy_email": "privacy@ecosia.org", "privacy_url": "https://info.ecosia.org/privacy", "method": "email", "risk_level": "low", "notes": "Tree-planting search engine. Uses Bing results. Anonymizes searches after 7 days.", "pack": "search"},
  {"id": "ask", "name": "Ask.com (IAC)", "category": "search", "privacy_email": "privacy@ask.com", "privacy_url": "https://www.ask.com/privacy", "method": "email", "risk_level": "moderate", "notes": "Search engine owned by IAC. Collects search queries, device data, and browsing behavior for ad serving.", "pack": "search"},
  {"id": "yandex", "name": "Yandex", "category": "search", "privacy_email": "privacy@yandex.com", "privacy_url": "https://yandex.com/legal/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Russian search engine. Operates maps, email, browser. Subject to Russian data laws. Collects extensive user data.", "pack": "search"},

  {"id": "home_depot", "name": "Home Depot", "category": "retail", "privacy_email": "privacy@homedepot.com", "privacy_url": "https://www.homedepot.com/privacy/privacy-and-security-statement", "method": "email", "risk_level": "moderate", "notes": "Home improvement retailer. Collects purchase history, Pro account details, app usage, and location data.", "pack": "retail"},
  {"id": "costco", "name": "Costco", "category": "retail", "privacy_email": "memberservices@costco.com", "privacy_url": "https://www.costco.com/privacy-policy.html", "method": "email", "risk_level": "moderate", "notes": "Wholesale retailer. Membership model means detailed purchase tracking. Shares data with Instacart for delivery.", "pack": "retail"},
  {"id": "best_buy", "name": "Best Buy", "category": "retail", "privacy_email": "privacymanager@bestbuy.com", "privacy_url": "https://www.bestbuy.com/site/privacy-policy/california-privacy-rights/pcmcat778200050003.c", "method": "email", "risk_level": "moderate", "notes": "Electronics retailer. Tracks browsing, purchase history, Geek Squad interactions, and Total Tech membership data.", "pack": "retail"},
  {"id": "kroger", "name": "Kroger", "category": "retail", "privacy_email": "privacy.office@kroger.com", "privacy_url": "https://www.kroger.com/i/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Largest US grocery chain. Loyalty card tracks every purchase. Launched Kroger Precision Marketing selling shopper data to CPG brands.", "pack": "retail"},
  {"id": "cvs", "name": "CVS Health", "category": "retail", "privacy_email": "privacy.officer@cvshealth.com", "privacy_url": "https://www.cvs.com/help/privacy_policy.jsp", "method": "email", "risk_level": "high_priority", "notes": "Pharmacy and health retailer. Collects prescription history, health purchases, ExtraCare loyalty data, and Aetna insurance data.", "pack": "retail"},
  {"id": "walgreens", "name": "Walgreens", "category": "retail", "privacy_email": "privacy.office@walgreens.com", "privacy_url": "https://www.walgreens.com/topic/help/generalhelp/privacyandsecurity.jsp", "method": "email", "risk_level": "high_priority", "notes": "Pharmacy chain. Tracks prescription history, health purchases, Balance Rewards loyalty program data.", "pack": "retail"},
  {"id": "sephora", "name": "Sephora", "category": "retail", "privacy_email": "privacy@sephora.com", "privacy_url": "https://www.sephora.com/beauty/privacy-policy", "method": "email", "risk_level": "moderate", "notes": "Beauty retailer. Fined $1.2M by CA AG in 2022 for CCPA violations (selling data without disclosure). Collects purchase and browsing behavior.", "pack": "retail"},

  {"id": "foursquare", "name": "Foursquare", "category": "location_broker", "privacy_email": "privacy@foursquare.com", "privacy_url": "https://foursquare.com/legal/privacy", "method": "email", "risk_level": "critical", "notes": "Location intelligence company. Tracks foot traffic for 500K+ businesses. SDK embedded in hundreds of popular apps collecting background location.", "pack": "location_brokers"},
  {"id": "arity", "name": "Arity (Allstate)", "category": "location_broker", "privacy_email": "privacy@arity.com", "privacy_url": "https://www.arity.com/privacy-policy/", "method": "email", "risk_level": "high_priority", "notes": "Allstate subsidiary. Collects driving behavior data from insurance apps and connected cars. 40M+ driver profiles.", "pack": "location_brokers"},
  {"id": "precisely", "name": "Precisely (Pitney Bowes)", "category": "location_broker", "privacy_email": "privacy@precisely.com", "privacy_url": "https://www.precisely.com/legal/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Location and data enrichment company. Processes geospatial data, demographics, and consumer behavior for enterprise clients.", "pack": "location_brokers"},
  {"id": "here_tech", "name": "HERE Technologies", "category": "location_broker", "privacy_email": "privacy@here.com", "privacy_url": "https://legal.here.com/privacy", "method": "email", "risk_level": "high_priority", "notes": "Mapping and location platform (owned by German auto consortium). Collects probe data from millions of vehicles and phones.", "pack": "location_brokers"},
  {"id": "tomtom", "name": "TomTom", "category": "location_broker", "privacy_email": "privacy@tomtom.com", "privacy_url": "https://www.tomtom.com/privacy/", "method": "email", "risk_level": "moderate", "notes": "Navigation and mapping company. Collects driving patterns, traffic data, and location history from navigation devices and apps.", "pack": "location_brokers"},

  {"id": "thomson_reuters", "name": "Thomson Reuters (CLEAR)", "category": "data_broker", "privacy_email": "privacy.enquiries@thomsonreuters.com", "privacy_url": "https://www.thomsonreuters.com/en/privacy-statement.html", "method": "email", "risk_level": "high_priority", "notes": "CLEAR investigative platform. Contains records on millions of people including addresses, phone numbers, assets, associates, criminal records.", "pack": "critical"},
  {"id": "kochava", "name": "Kochava", "category": "data_broker", "privacy_email": "privacy@kochava.com", "privacy_url": "https://www.kochava.com/privacy-policy/", "method": "email", "risk_level": "critical", "notes": "Mobile attribution and data marketplace. FTC sued in 2022 for selling geolocation data that could track visits to reproductive health clinics.", "pack": "critical"},
  {"id": "verisk", "name": "Verisk Analytics", "category": "data_broker", "privacy_email": "privacy@verisk.com", "privacy_url": "https://www.verisk.com/privacy-policies/", "method": "email", "risk_level": "high_priority", "notes": "Insurance data analytics. Maintains claims databases, property records, and risk scores used by insurers to set premiums.", "pack": "critical"},
  {"id": "neustar", "name": "Neustar (TransUnion)", "category": "data_broker", "privacy_email": "privacy@team.neustar", "privacy_url": "https://www.home.neustar/privacy", "method": "email", "risk_level": "high_priority", "notes": "Identity resolution and marketing analytics. Acquired by TransUnion. Links online behavior to real-world identities.", "pack": "critical"},
  {"id": "towerdata", "name": "TowerData", "category": "data_broker", "privacy_email": "privacy@towerdata.com", "privacy_url": "https://www.towerdata.com/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Email intelligence company. Appends demographic, interest, and purchase data to email addresses for marketers.", "pack": "critical"},
  {"id": "fullcontact", "name": "FullContact", "category": "data_broker", "privacy_email": "privacy@fullcontact.com", "privacy_url": "https://www.fullcontact.com/privacy/", "method": "email", "risk_level": "high_priority", "notes": "Identity resolution API. Enriches email addresses and phone numbers with social profiles, demographics, and interests.", "pack": "critical"},
  {"id": "zoominfo", "name": "ZoomInfo", "category": "data_broker", "privacy_email": "privacy@zoominfo.com", "privacy_url": "https://www.zoominfo.com/about/privacy-center", "method": "email", "risk_level": "high_priority", "notes": "B2B contact database. Collects work email, phone, job title, company data on 100M+ professionals from web scraping and data partnerships.", "pack": "critical"},
  {"id": "datatrade", "name": "Datarade (Marketplace)", "category": "data_broker", "privacy_email": "privacy@datarade.ai", "privacy_url": "https://datarade.ai/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Data marketplace connecting buyers and sellers. Lists 2000+ data products including location, identity, and behavioral datasets.", "pack": "critical"},

  {"id": "threads", "name": "Threads (Meta)", "category": "social_media", "privacy_email": "privacy@meta.com", "privacy_url": "https://help.instagram.com/515230437301944", "method": "email", "risk_level": "high_priority", "notes": "Meta's Twitter competitor. Inherits Instagram's data collection practices. Collects device data, contacts, browsing, and content interactions.", "pack": "social"},
  {"id": "bluesky", "name": "Bluesky", "category": "social_media", "privacy_email": "privacy@bsky.app", "privacy_url": "https://bsky.social/about/support/privacy-policy", "method": "email", "risk_level": "low", "notes": "Decentralized social network. Open protocol (AT Protocol). Minimal data collection compared to centralized alternatives.", "pack": "social"},
  {"id": "mastodon", "name": "Mastodon (joinmastodon.org)", "category": "social_media", "privacy_email": "privacy@joinmastodon.org", "privacy_url": "https://joinmastodon.org/privacy-policy", "method": "email", "risk_level": "low", "notes": "Federated social network. Data stored on individual servers. Request goes to your instance admin, not a central company.", "pack": "social"},
  {"id": "bumble", "name": "Bumble", "category": "social_media", "privacy_email": "DPO@team.bumble.com", "privacy_url": "https://bumble.com/privacy", "method": "email", "risk_level": "high_priority", "notes": "Dating app collecting photos, location, preferences, messaging content, device data, and behavioral patterns.", "pack": "social"},
  {"id": "match_group", "name": "Match Group (Tinder/Hinge)", "category": "social_media", "privacy_email": "privacy@match.com", "privacy_url": "https://www.match.com/privacy", "method": "email", "risk_level": "high_priority", "notes": "Owns Tinder, Hinge, OkCupid, Match. Collects intimate personal data including preferences, photos, messages, location, sexual orientation.", "pack": "social"},

  {"id": "google_deepmind", "name": "Google DeepMind", "category": "ai_company", "privacy_email": "privacy@google.com", "privacy_url": "https://deepmind.google/about/privacy/", "method": "email", "risk_level": "high_priority", "notes": "DeepMind AI research lab (Alphabet). Uses data to train AI models including Gemini. Previously accessed NHS patient records.", "pack": "ai"},
  {"id": "amazon_ai", "name": "Amazon (Alexa AI)", "category": "ai_company", "privacy_email": "privacy@amazon.com", "privacy_url": "https://www.amazon.com/hz/privacycentral", "method": "email", "risk_level": "critical", "notes": "Alexa voice recordings, Ring camera footage, purchase history, and browsing all feed Amazon's AI training and ad targeting.", "pack": "ai"},
  {"id": "ibm_watson", "name": "IBM Watson", "category": "ai_company", "privacy_email": "privacy@ibm.com", "privacy_url": "https://www.ibm.com/privacy", "method": "email", "risk_level": "moderate", "notes": "Enterprise AI platform. Processes client data for AI training. Watson Health division handles sensitive medical records.", "pack": "ai"},
  {"id": "palantir_aip", "name": "Palantir AIP", "category": "ai_company", "privacy_email": "privacy@palantir.com", "privacy_url": "https://www.palantir.com/privacy-and-security/", "method": "email", "risk_level": "critical", "notes": "AI Platform for government and enterprise. Foundry and AIP process vast datasets including personal data. US military and ICE contractor.", "pack": "ai"},
  {"id": "clearview_training", "name": "Clearview AI (Training Data)", "category": "ai_company", "privacy_email": "privacy@clearview.ai", "privacy_url": "https://www.clearview.ai/privacy-policy", "method": "email", "risk_level": "critical", "notes": "Scraped 30B+ photos from social media to train facial recognition. AI model trained on your face without consent. Request covers training data deletion.", "pack": "ai"},
  {"id": "scale_ai", "name": "Scale AI", "category": "ai_company", "privacy_email": "privacy@scale.com", "privacy_url": "https://scale.com/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "AI data labeling company. Processes images, text, and video containing personal data to train AI models for government and enterprise clients.", "pack": "ai"},

  {"id": "talkspace", "name": "Talkspace", "category": "health_data", "privacy_email": "privacy@talkspace.com", "privacy_url": "https://www.talkspace.com/public/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Online therapy platform. Collects therapy session transcripts, mental health assessments, and personal disclosures.", "pack": "health"},
  {"id": "teladoc", "name": "Teladoc Health", "category": "health_data", "privacy_email": "privacy@teladochealth.com", "privacy_url": "https://www.teladochealth.com/privacy-policy/", "method": "email", "risk_level": "high_priority", "notes": "Telehealth platform. Collects medical consultations, prescriptions, and health records from virtual visits.", "pack": "health"},
  {"id": "apple_health", "name": "Apple Health", "category": "health_data", "privacy_email": "privacy@apple.com", "privacy_url": "https://www.apple.com/privacy/", "method": "email", "risk_level": "low", "notes": "Health data stored on device with end-to-end encryption. Apple cannot access it. Included for completeness.", "pack": "health"},
  {"id": "withings", "name": "Withings", "category": "health_data", "privacy_email": "privacy@withings.com", "privacy_url": "https://www.withings.com/privacy", "method": "email", "risk_level": "moderate", "notes": "Smart scale, blood pressure monitor, and sleep tracker manufacturer. Cloud-synced health data stored on French servers.", "pack": "health"},
  {"id": "hims_hers", "name": "Hims & Hers", "category": "health_data", "privacy_email": "privacy@forhims.com", "privacy_url": "https://www.forhims.com/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Telehealth and prescription service. Collects health questionnaires, prescriptions, and personal health data.", "pack": "health"},
  {"id": "invitae", "name": "Invitae (genetic testing)", "category": "health_data", "privacy_email": "privacy@invitae.com", "privacy_url": "https://www.invitae.com/en/privacy", "method": "email", "risk_level": "critical", "notes": "Genetic testing company. Collects DNA sequences and health history. Genetic data is the most permanent personal data that exists.", "pack": "health"},

  {"id": "hikvision", "name": "Hikvision", "category": "surveillance", "privacy_email": "privacy@hikvision.com", "privacy_url": "https://www.hikvision.com/en/privacy-policy/", "method": "email", "risk_level": "critical", "notes": "World's largest surveillance camera manufacturer. Chinese state-owned. FCC banned from US government use. Cameras deployed in many US businesses.", "pack": "surveillance"},
  {"id": "dahua", "name": "Dahua Technology", "category": "surveillance", "privacy_email": "privacy@dahuatech.com", "privacy_url": "https://www.dahuasecurity.com/privacy", "method": "email", "risk_level": "critical", "notes": "Second-largest surveillance camera maker. Chinese state-owned. Sanctioned by US government. Cameras still widely sold in US retail.", "pack": "surveillance"},
  {"id": "briefcam", "name": "BriefCam (Canon)", "category": "surveillance", "privacy_email": "privacy@briefcam.com", "privacy_url": "https://www.briefcam.com/privacy-policy/", "method": "email", "risk_level": "high_priority", "notes": "Video analytics and facial recognition platform owned by Canon. Used by law enforcement for retroactive surveillance analysis.", "pack": "surveillance"},
  {"id": "voyager_labs", "name": "Voyager Labs", "category": "surveillance", "privacy_email": "privacy@voyagerlabs.co", "privacy_url": "https://voyagerlabs.co/privacy-policy/", "method": "email", "risk_level": "critical", "notes": "Social media surveillance company. Creates fake accounts to monitor targets. Used by LAPD and other law enforcement agencies.", "pack": "surveillance"},
  {"id": "sandvine", "name": "Sandvine", "category": "surveillance", "privacy_email": "privacy@sandvine.com", "privacy_url": "https://www.sandvine.com/privacy-policy", "method": "email", "risk_level": "high_priority", "notes": "Deep packet inspection company. Technology used by governments to monitor, throttle, and censor internet traffic.", "pack": "surveillance"},
  {"id": "checkpeople", "name": "CheckPeople", "category": "data_broker", "privacy_email": "", "privacy_url": "https://checkpeople.com/opt-out", "method": "portal", "risk_level": "high_priority", "notes": "People search site compiling background records. To opt out, complete the forms requiring birthdate and full legal name.", "pack": "critical"},
  {"id": "clustal", "name": "Clustal.org", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.clustal.org/privacy-control", "method": "portal", "risk_level": "high_priority", "notes": "People search directory. Search your name, click view full record to grab the final URL, and paste it on their privacy control page.", "pack": "critical"},
  {"id": "menstoppingviolence", "name": "Men Stopping Violence", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.menstoppingviolence.org/opt-out/", "method": "portal", "risk_level": "high_priority", "notes": "People search database. Find your profile listing on their people directory, then submit the URL to their opt-out portal to request removal.", "pack": "critical"},
  {"id": "nuwber", "name": "Nuwber", "category": "data_broker", "privacy_email": "support@nuwber.com", "privacy_url": "https://nuwber.com/removal/link", "method": "email", "risk_level": "high_priority", "notes": "People search directory. Fill out the removal link form with your profile URL. Email support@nuwber.com directly if the form fails.", "pack": "critical"},
  {"id": "smartbackgroundchecks", "name": "SmartBackgroundChecks", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.smartbackgroundchecks.com/optout", "method": "portal", "risk_level": "high_priority", "notes": "Free people search engine. Completing the opt-out also removes your details from PeopleFinders.", "pack": "critical"},
  {"id": "thatsthem", "name": "That's Them", "category": "data_broker", "privacy_email": "", "privacy_url": "https://thatsthem.com/optout", "method": "portal", "risk_level": "high_priority", "notes": "Aggregates physical addresses, emails, phone numbers, and IP addresses. Opt out via their online form.", "pack": "critical"},
  {"id": "advancedbackgroundchecks", "name": "AdvancedBackgroundChecks", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.advancedbackgroundchecks.com/opt-out", "method": "portal", "risk_level": "high_priority", "notes": "Large people search database. Submit your email on the opt-out page, then click the link in your inbox to verify removal.", "pack": "critical"},
  {"id": "familytreenow", "name": "FamilyTreeNow", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.familytreenow.com/optout", "method": "portal", "risk_level": "high_priority", "notes": "Displays extensive lists of living relatives, associates, and physical address history for free. Opt out via the online portal.", "pack": "critical"},
  {"id": "fastpeoplesearch", "name": "FastPeopleSearch", "category": "data_broker", "privacy_email": "", "privacy_url": "https://www.fastpeoplesearch.com/optout", "method": "portal", "risk_level": "high_priority", "notes": "Popular free public records search. Submit your profile for removal via their web form, solving the captcha.", "pack": "critical"},
  {"id": "usphonebook", "name": "USPhoneBook", "category": "data_broker", "privacy_email": "support+optout@usphonebook.com", "privacy_url": "https://www.usphonebook.com/opt-out/", "method": "email", "risk_level": "high_priority", "notes": "Phone directory records. Opt out via their web form, or email support+optout@usphonebook.com directly if the form hangs.", "pack": "critical"}
]
;
